# Generated by Django 3.2.6 on 2021-08-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitCoinExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_name', models.CharField(max_length=20)),
                ('to_currency_name', models.CharField(max_length=20)),
                ('exchange_rate', models.FloatField()),
                ('last_updates_ts', models.DateTimeField()),
                ('time_zone', models.CharField(max_length=8)),
            ],
        ),
    ]
